spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/class?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: root

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
      org.hibernate.envers:
        audit_table_suffix: History
        revision_field_name: revisionId
        revision_type_field_name: revisionType
        store_data_at_delete: true
    database-platform: org.hibernate.dialect.MySQLDialect
    defer-datasource-initialization: false
  redis:
    host: localhost
    port: 6379

security:
  jwt:
    token:
      secret-key: "D1E0E7FB4E39EA05CF1A7F5AC77221ECF16117D4390A10291E94563913D663F8"

logging:
  level:
    root: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

